version: "3.7"
services:
  postgres:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_DB=vyrix
      - POSTGRES_USER=vyrix
      - POSTGRES_PASSWORD=Tunjozmaj123
    ports:
      - "8081:5432"
    volumes:
      - postgres:/var/lib/db
    networks:
      vyrix-net:
        aliases:
          - postgres

volumes:
  postgres: