# Generated by Django 3.1.1 on 2020-09-09 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='the title of the permission', max_length=120)),
                ('identifier', models.CharField(help_text='the identifier of the permission, has to be unique', max_length=40, unique=True)),
                ('description', models.TextField(default='', help_text='further description of the permission')),
            ],
        ),
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(help_text='the permission the user owns', on_delete=django.db.models.deletion.CASCADE, to='kgv.permission')),
                ('user', models.ForeignKey(help_text='the user who owns a permission', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'permission')},
            },
        ),
    ]
